services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: EatFit_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: danik22081
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    image: parodia/eatfit:0.0.1-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=dockermvn
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/EatFit_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=danik22081
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
